import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/header";
import Footer from "./components/shared/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubic = Rubik({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
  keywords: [
    "Next.js",
    "React",
    "TypeScript",
    "TailwindCSS",
    "ToDo",
    "ToDo",
    "App",
    "List",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubic.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header title="ToDo App" />
        {children}
        <Footer title="Todos os direitos reservados - ToDo App" />
      </body>
    </html>
  );
}
